/*
* @author: Group 15 - Advanced System Programming
* @date: 2017-03-22
* @description: This is the client part of the project...It connects
*               to a specific port that is generated by the server.
*/

//Including the necessary files for the script
#include <sys/types.h>
#include <sys/socket.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <arpa/inet.h>
#include <time.h>
#include <sys/prctl.h>
#include <sys/signal.h>

//Declaring global variables
char message[255];
pid_t pid;
int server, portNumber;
socklen_t len;
struct sockaddr_in servAdd;
char *myTime;
time_t currentUnixTime;

//main function
int main(int argc, char *argv[])
{
  //Varibale that holds the username and the final byte of data that was sent to the server
  char uname[20];
	char sender[40];

  //If the number of arguements supplied by the client is not equal to 3:
	if(argc != 3)
	{
		printf("Call model:%s <IP> <Port#>\n",argv[0]);
		exit(0);
	}

  //Creating a client socket
	if((server = socket(AF_INET, SOCK_STREAM, 0))<0)
	{
		fprintf(stderr, "Cannot create socket\n");
		exit(1);
	}

  //Creating the server varibles...
	servAdd.sin_family = AF_INET;
	sscanf(argv[2], "%d", &portNumber);
	servAdd.sin_port = htons((uint16_t)portNumber);

	if(inet_pton(AF_INET,argv[1],&servAdd.sin_addr)<0)
	{
		fprintf(stderr, " inet_pton() has failed\n");
		exit(2);
	}

  //Connecting to the server
	if(connect(server,(struct sockaddr *)&servAdd,sizeof(servAdd))<0)
	{
		fprintf(stderr, "connect() has failed, exiting\n");
		exit(3);
	}




	//Create a new process: One for reading from the server
  //The other for writing to the server
	pid = fork();

  //get the client credentials
  getlogin_r(uname, sizeof(uname));
  strcpy( sender, uname);
  strcat( sender, " has connected \n\n");

  //Send the client credentials to the server
  write(server, sender, strlen(sender)+1);

	//This switch-case statement executes depending on
  //The outcome of the fork command
	switch (pid)
	 {
		case -1:
				perror("fork() error: Process could not be created");
				exit(EXIT_FAILURE);
		case 0:
				prctl(PR_SET_PDEATHSIG, SIGHUP);
        //loops continously to get a message from the server
				while(1)
				 {
						if(read(server, message, 255)<0)
						{
							fprintf(stderr, "read() error: \n");
							exit(3);
						}
            //show the client the messgae that was gotten from the server
						fprintf(stderr, "%s\n",message);
            //wait for three seconds and read again...
						sleep(3);
				}
				exit(0);
		default:
        //Prints a kinda welcome message to the client...
        fprintf(stderr, "\n\n %s \n\n","************* Welcome to Chat Application *************");
        fprintf(stderr, "%s \n\n","!!!!!! To quit anytime, Please press $ !!!!!!");

        //trying to get the message from the client and send to the server...
      	while(1)
				{
          //get the strings from the client...
					fgets(message, 254, stdin);

          //If the client entered $, exit the chat and kill the particular process
					if(message[0] == '$')
					{
						kill(getpid(), SIGKILL);
						close(server);
						exit(0);
					}

          //format Time
          currentUnixTime = time(NULL);
      		myTime = ctime(&currentUnixTime);
          getlogin_r(uname, sizeof(uname));

          //format the string before sending them to the server
					strcpy( sender, uname);
					strcat( sender, " said: ");
					strcat( sender,message);
          strcat( sender,"On: ");
          strcat( sender,myTime);

          //Send a message to the server
					write(server, sender, strlen(sender)+1);
				}
				exit(0);
		}
}
