/*
* @author: Group 15 - Advanced System Programming
* @date: 2017-03-22
* @description: This is the server part of the project...It generates
*               to a specific port that is generated by the server.
*/
#include <sys/types.h>
#include <sys/socket.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <arpa/inet.h>
#include <time.h>
#include <fcntl.h>
#include <pthread.h>

//creating static variables...
int clients[10];
int counter = 0;

//Create a function for the thread...
void* mini_server(void* data){

	int *clientDescriptor;
	clientDescriptor = (int*)data;
	char message[255];

	while(1)
	{
		//Reading a message from the client
		if(!read(clientDescriptor, message, 255))
		{
			//if no data could be read, then the client has exited...exit the thread
			fprintf(stderr,"Bye, client %d just exited.\n",clientDescriptor);
			pthread_exit(NULL); //exiting the thread
		}

		//If the message was gotten from the client
		printf("Got a message from client : %d\n",clientDescriptor);
		int a;

		//send the message to all the connected clients except the
		//current client....
		for(a = 0 ; a < counter; a++){
       if(clientDescriptor != clients[a]){
					 write(clients[a], message, strlen(message)+1);
					 printf("<<< Broadcasting the message to client %d >>>\n",clients[a]);
			 }
		}
		//wait for three seconds and go to read again...
		sleep(3);
	}
}

int main(int argc, char *argv[])
{
	int sd, client, portNumber;
	socklen_t len;
	struct sockaddr_in servAdd;
	int fileDescriptor;
	pthread_t threads[5];

	if(argc != 2)
	{
		printf("Call model: %s <Port #>\n", argv[0]);
		exit(0);
	}

	if ((sd=socket(AF_INET,SOCK_STREAM,0))<0)
	{
		fprintf(stderr, "Cannot create socket\n");
		exit(1);
	}

	servAdd.sin_family = AF_INET;
	servAdd.sin_addr.s_addr = htonl(INADDR_ANY);
	sscanf(argv[1], "%d", &portNumber);
	servAdd.sin_port = htons((uint16_t)portNumber);
	bind(sd,(struct sockaddr*)&servAdd,sizeof(servAdd));
	listen(sd, 5);
  printf("server running on port %d \n",portNumber);
	while(1)
	{
		//waiting to get a client...
		client=accept(sd,(struct sockaddr*)NULL,NULL);

		//alert the server that it got a client...
		printf("Got a client\n");

		//check if more than one client has connected
		if(counter > 0){
				write(client, "start chatting", 16);
		}else{
				write(client, "Please wait for other clients to connect", 40);
		}

		//insert the client description into the clients array
		clients[counter] = client;
		//create a thread for the client...
		pthread_create(&threads[counter], NULL, mini_server, client);
		//increment the counter index
		counter = counter+1;
	}

}
